apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-messi
  namespace: messi-dev2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.cpaas.nutanix.com/app: test-messi
    k8s.cpaas.nutanix.com/deployment-name: test-messi
    k8s.cpaas.nutanix.com/product: messi
    k8s.cpaas.nutanix.com/programming-language: golang
    k8s.cpaas.nutanix.com/team: team1
    k8s.cpaas.nutanix.com/workload-resource-type: general
  name: test-messi
  namespace: messi-dev2
spec:
  replicas: 0
  selector:
    matchLabels:
      k8s.cpaas.nutanix.com/deployment-name: test-messi
      k8s.cpaas.nutanix.com/product: messi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        k8s.cpaas.nutanix.com/app: test-messi
        k8s.cpaas.nutanix.com/deployment-name: test-messi
        k8s.cpaas.nutanix.com/product: messi
        k8s.cpaas.nutanix.com/programming-language: golang
        k8s.cpaas.nutanix.com/team: team1
        k8s.cpaas.nutanix.com/workload-resource-type: general
    spec:
      containers:
        - args: []
          command: []
          env:
            - name: OTEL_HOST
              value: http://localhost:4317
          envFrom: []
          image: aws@123
          imagePullPolicy: IfNotPresent
          name: aws
          ports: []
          resources:
            limits:
              cpu: 200.000000m
              ephemeral-storage: 2000.000000Mi
              memory: 500.000000Mi
            requests:
              cpu: 100.000000m
              ephemeral-storage: 1000.000000Mi
              memory: 200.000000Mi
          volumeMounts: []
      initContainers: []
      nodeSelector: {}
      serviceAccountName: test-messi
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: messi
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              k8s.cpaas.nutanix.com/deployment-name: test-messi
              k8s.cpaas.nutanix.com/product: messi
          maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: ScheduleAnyway
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: test-messi
  name: test-messi
  namespace: messi-dev2
spec:
  ports:
    - name: test-product
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s.cpaas.nutanix.com/deployment-name: test-messi
    k8s.cpaas.nutanix.com/product: messi
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    k8s.cpaas.nutanix.com/app: test-messi
    k8s.cpaas.nutanix.com/deployment-name: test-messi
    k8s.cpaas.nutanix.com/product: messi
    k8s.cpaas.nutanix.com/programming-language: golang
    k8s.cpaas.nutanix.com/team: team1
    k8s.cpaas.nutanix.com/workload-resource-type: general
  name: test-messi
  namespace: messi-dev2
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      clutch.pdb: inactive
      k8s.cpaas.nutanix.com/deployment-name: test-messi
      k8s.cpaas.nutanix.com/product: messi
