apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: messi-qa9
  namespace: argocd
spec:
  destination:
    name: india
    namespace: default
  project: messi
  source:
    path: products/messi/manifests/qa9/
    plugin:
      name: argocd-vault-plugin
    repoURL: git@github.com:KrishnaSindhur/clutch-test4
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
