apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test2-rbac-viewer
  namespace: messi-test2
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/portforward
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-test2-rbac-viewer
  namespace: messi-test2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test2-rbac-viewer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: CPaaS-stage-messi-viewer
